name: the_conduit
description: "A secure communications application."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Theming
  google_fonts: ^6.1.0 
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  flutter_slidable: ^3.0.0
  photo_view: ^0.14.0
  collection: ^1.18.0

  # State Management
  flutter_riverpod: ^2.4.9

  # Cryptography & Security
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0  # Includes support for enhanced options
  uuid: ^4.5.1
  cryptography: ^2.5.0
  biometric_storage: ^5.0.0+4  # Added for biometric-secured data
  local_auth: ^2.1.8  # Added for biometric authentication

  # Database
  sembast: ^3.6.0
  sembast_web: ^2.2.0
  url_launcher: ^6.1.14

  # Firebase
  cloud_firestore: ^4.17.5
  firebase_core: 2.32.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.5
  firebase_crashlytics: ^3.4.19  # Added for crash reporting

  # Other utilities
  intl: ^0.19.0
  path_provider: ^2.0.11
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  permission_handler: ^11.0.1
  animated_text_kit: ^4.2.2
  logger: ^2.0.1
  share_plus: ^7.2.1
  universal_html: ^2.2.4
  image: ^4.0.17
  device_info_plus: ^11.3.0
  mime: ^1.0.6
  path: ^1.9.0
  connectivity_plus: ^6.1.4
  video_player: ^2.9.5
  fluttertoast: ^8.2.4  # Added for toast messages
  http: ^1.2.1  # Added for HTTP requests
  flutter_dotenv: ^5.1.0  # Added for environment variable management

  open_file_plus: ^3.4.1+1
  dio: ^5.8.0+1
  package_info_plus: ^8.3.0

  # Background services
  flutter_background_service: ^5.0.5
  workmanager: ^0.5.2  # Added for background tasks
  audioplayers: ^6.4.0

  # App Security
  flutter_jailbreak_detection: ^1.10.0  # Added for root/jailbreak detection
  flutter_secure_keyboard: ^2.0.0  # Added for secure keyboard input

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  # Added for app icon generation
  build_runner: ^2.4.8  # Added for code generation

flutter:
  uses-material-design: true