// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUJ7sFQ0qSE26zel5qw3AH9j5xGTWi6kY',
    appId: '1:219570465125:web:25b883f6834aa37004598c',
    messagingSenderId: '219570465125',
    projectId: 'encriptapp-90906',
    authDomain: 'encriptapp-90906.firebaseapp.com',
    storageBucket: 'encriptapp-90906.firebasestorage.app',
    measurementId: 'G-VJ7Q5ZV8RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXENFCyopftFsqVu7lk5MQ_Df0fmHFS0E',
    appId: '1:219570465125:android:dc18eb3ee254c8e404598c',
    messagingSenderId: '219570465125',
    projectId: 'encriptapp-90906',
    storageBucket: 'encriptapp-90906.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBFtalCUcuploPo_Fg7314ClZPFnCUZ4g',
    appId: '1:219570465125:ios:35a10c70c1aff88904598c',
    messagingSenderId: '219570465125',
    projectId: 'encriptapp-90906',
    storageBucket: 'encriptapp-90906.firebasestorage.app',
    iosBundleId: 'y',
  );
}
